require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProductLogsController do

  # This should return the minimal set of attributes required to create a valid
  # ProductLog. As you add validations to ProductLog, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductLogsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all product_logs as @product_logs" do
      product_log = ProductLog.create! valid_attributes
      get :index, {}, valid_session
      assigns(:product_logs).should eq([product_log])
    end
  end

  describe "GET show" do
    it "assigns the requested product_log as @product_log" do
      product_log = ProductLog.create! valid_attributes
      get :show, {:id => product_log.to_param}, valid_session
      assigns(:product_log).should eq(product_log)
    end
  end

  describe "GET new" do
    it "assigns a new product_log as @product_log" do
      get :new, {}, valid_session
      assigns(:product_log).should be_a_new(ProductLog)
    end
  end

  describe "GET edit" do
    it "assigns the requested product_log as @product_log" do
      product_log = ProductLog.create! valid_attributes
      get :edit, {:id => product_log.to_param}, valid_session
      assigns(:product_log).should eq(product_log)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProductLog" do
        expect {
          post :create, {:product_log => valid_attributes}, valid_session
        }.to change(ProductLog, :count).by(1)
      end

      it "assigns a newly created product_log as @product_log" do
        post :create, {:product_log => valid_attributes}, valid_session
        assigns(:product_log).should be_a(ProductLog)
        assigns(:product_log).should be_persisted
      end

      it "redirects to the created product_log" do
        post :create, {:product_log => valid_attributes}, valid_session
        response.should redirect_to(ProductLog.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved product_log as @product_log" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductLog.any_instance.stub(:save).and_return(false)
        post :create, {:product_log => {}}, valid_session
        assigns(:product_log).should be_a_new(ProductLog)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductLog.any_instance.stub(:save).and_return(false)
        post :create, {:product_log => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested product_log" do
        product_log = ProductLog.create! valid_attributes
        # Assuming there are no other product_logs in the database, this
        # specifies that the ProductLog created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProductLog.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => product_log.to_param, :product_log => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested product_log as @product_log" do
        product_log = ProductLog.create! valid_attributes
        put :update, {:id => product_log.to_param, :product_log => valid_attributes}, valid_session
        assigns(:product_log).should eq(product_log)
      end

      it "redirects to the product_log" do
        product_log = ProductLog.create! valid_attributes
        put :update, {:id => product_log.to_param, :product_log => valid_attributes}, valid_session
        response.should redirect_to(product_log)
      end
    end

    describe "with invalid params" do
      it "assigns the product_log as @product_log" do
        product_log = ProductLog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductLog.any_instance.stub(:save).and_return(false)
        put :update, {:id => product_log.to_param, :product_log => {}}, valid_session
        assigns(:product_log).should eq(product_log)
      end

      it "re-renders the 'edit' template" do
        product_log = ProductLog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductLog.any_instance.stub(:save).and_return(false)
        put :update, {:id => product_log.to_param, :product_log => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested product_log" do
      product_log = ProductLog.create! valid_attributes
      expect {
        delete :destroy, {:id => product_log.to_param}, valid_session
      }.to change(ProductLog, :count).by(-1)
    end

    it "redirects to the product_logs list" do
      product_log = ProductLog.create! valid_attributes
      delete :destroy, {:id => product_log.to_param}, valid_session
      response.should redirect_to(product_logs_url)
    end
  end

end
